* Tree-promote

Promote and demote a tree for  quick and easy code manipulation. Think
org-mode, but for code.

Meant for indentation-based languages.

Warning: horrible and rough implementation, but yet super great !

Example:

#+BEGIN_SRC python
def foo(): # <- point on this line, call M-x tree-promote
    pass
print
#+END_SRC
you get
#+BEGIN_SRC python
    def foo():
        pass
print
#+END_SRC

** Usage

Evaluate the buffer and call
: M-x tree-promote

Shortcut put at =C-c >=.

Incoming: select the indentation yourself (as does =M-x indent-rigidly=).

*** Comment the tree

=tree-promote-comment=

** Implementation

- let "beg" be the first point of the current line
- press the down arrow until we find a non-blank character
- let "end" be the last point of that line
- indent the region between "beg" and "end".

** Ideas, todos

Demote.

Indent according to mode.

Do something with the default  behaviour of =M-x indent-rigidly= which
lets us indent interactively. Would be useful for jade templates.

See if  the utilities functions  of mine  on [[https://gitlab.com/emacs-stuff/my-elisp/blob/master/yaml-utils.el][yaml-utils]] can  be useful
(indent all siblings at once ?).

See `move-text` in melpa to move regions up and down.
